### ISSUE TITLE
Support "serve" and "run" like the Webpack module?

### ISSUE THREAD

**Issue by kopertop** [graphcool/serverless-plugin-typescript#12]
Question: Would it be good to add things like the "[serve](https://github.com/elastic-coders/serverless-webpack/blob/master/lib/serve.js)" and "[run](https://github.com/elastic-coders/serverless-webpack/blob/master/lib/run.js)" function from Webpack?

I need to test things locally, and this might be a good way to go if we can't integrate natively with other modules like serverless-simulate or serverless-local. It's not a complete solution but might be a simpler option then running one of these other modules and supporting them directly.

**Comment by schickling** [comment]
I'd definitely favour a solution where we could re-use other existing best practises. I'm not familiar with the webpack plugin. Would be great to hear @pmuens opinion as well!

**Comment by pmuens** [comment]
> Would be great to hear @pmuens opinion as well!

Thanks for mentioning 👍 

Adding a `serve` option sounds like a nice addition and big DX win!

Just to be clear. The idea is to add an option like it's done in the webpack plugin but not an integration with the webpack plugin, correct?

**Comment by kopertop** [comment]
Yes, the plan here is to just add something like ```ts serve``` as a command directly, just borrowing from what the webpack module did.

I originally was trying out the webpack module but it wasn't nearly as good as this module (even as simple as this module is!) but I loved the local invocation and serve capabilities.

Functions like "serverless-simulate" are too heavy for me (I'm running an old iMac), so something simple like this would be ideal for my dev situation.

**Comment by pmuens** [comment]
@kopertop gotcha! Yes, such a simple and lightweight addition sounds like a good plan! 👍

**Comment by RomanGotsiy** [comment]
@kopertop webpack-serverless [are going to deprecate server](https://github.com/elastic-coders/serverless-webpack#simulate-api-gateway-locally) in favor of using serverless-offline.

Latest version `1.0.0` of serverless integrates very well with `serverless-offline`.

As for `run` functionality you can use `sls invoke local -f <FnNam>`. `serverless-plugin-typescript` also supports it + it supports [`--watch` mode](https://github.com/graphcool/serverless-plugin-typescript#run-a-function-locally)

I would close the issue in favor of using `serverless-offline` + `serverless invoke local`

@schickling, @kopertop what do you think?

**Comment by schickling** [comment]
Let's re-open this if the DX turns out to be not good enough.
