### ISSUE TITLE
serverless deploy function -f functionName not working?

### ISSUE THREAD

**Issue by davepwsmith** [graphcool/serverless-plugin-typescript#15]
I don't seem to be able to use this with `serverless deploy function -f functionName` - I'm not sure what gets deployed, but whatever it is it doesn't work, and the `Compiling typescript` line doesn't come up in the command's output...

Awesome tool in general though!

**Comment by schickling** [comment]
Hi @davepwsmith. Thanks a lot for pointing this out. Would you be open for creating a PR supporting this functionality? Maybe also related to #10?

**Comment by NicholasDunham** [comment]
I've taken the liberty of submitting a PR—let me know if you have any questions. It looks to me like #10 is a separate issue; I plan to look into that further tomorrow.
