### ISSUE TITLE
Serverless Plugin warnings about deprecated hooks

### ISSUE THREAD

**Issue by ccannell** [graphcool/serverless-plugin-typescript#21]
When using the plugin against Serverless 1.15.3

`Serverless: WARNING: Plugin ServerlessPlugin uses deprecated hook before:deploy:createDeploymentArtifacts

Serverless: WARNING: Plugin ServerlessPlugin uses deprecated hook after:deploy:createDeploymentArtifacts`

**Comment by schickling** [comment]
@adieuadieu any thoughts?

**Comment by ccannell** [comment]
Unfortunately, I haven't worked with Serverless' plugin architecture so I don't immediately know how to fix this.

**Comment by ccannell** [comment]
These are currently supported hooks [https://serverless.com/framework/docs/providers/aws/guide/plugins#lifecycle-events](https://serverless.com/framework/docs/providers/aws/guide/plugins#lifecycle-events)

**Comment by adieuadieu** [comment]
@schickling Looks like the deploy hook was deprecated on May 23rd in [this commit](https://github.com/serverless/serverless/commit/d9637fc534e7c7d176e2e07b9b44a8a50561bebd#diff-d50cb54694de697bd8c73042567e1bf7). Well... I guess it's a good thing #20 was just merged! I think the [lifecycle-events](https://serverless.com/framework/docs/providers/aws/guide/plugins#lifecycle-events) documentation is probably outdated as it doesn't reflect the code in Serverless' master branch.

**Comment by schickling** [comment]
@ccannell can you install the newest version of the plugin and try again?

**Comment by ccannell** [comment]
Just tested. Warnings are gone. Thanks.
