### ISSUE TITLE
fs-p is deprecated

### ISSUE THREAD

**Issue by balassy** [graphcool/serverless-plugin-typescript#34]
When running `npm install` in a project that depends on `serverless-plugin-typescript`, npm throws the following warning:
```
npm WARN deprecated fs-p@2.0.0: Use fs-extra@4.0.0+ instead
```

Thank you for creating and updating this project!

**Comment by schickling** [comment]
Would you mind creating a PR replacing the dep?

**Comment by balassy** [comment]
Sure, here it is: #36.

Note that although I checked that all jest tests are passing, I could not thoroughly test the whole package.
