### ISSUE TITLE
How i can add additional files (.json/fonts/assets) to .build-folder?

### ISSUE THREAD

**Issue by mattmeye** [graphcool/serverless-plugin-typescript#60]
Hey, 

i use some additional fles in my typescript fles (jpgs, templates, fonts) to eg. create pdf files. While testing these files are not added to .build-folder automatically? how can i do this?

best regards

**Comment by bhasto** [comment]
I’ve encountered a similar problem. It helped to user Serverless’ include config: https://serverless.com/framework/docs/providers/aws/guide/packaging/#exclude--include

**Comment by mattmeye** [comment]
thank you!
