### ISSUE TITLE
sls invoke local does not work

### ISSUE THREAD

**Issue by kopertop** [graphcool/serverless-plugin-typescript#8]
I love this plugin, however it doesn't work with many other functions that make the serverless framework great, including other plugins, and even native functionality such as invoking the function locally.

Without being able to test locally, this plugin really reduces the benefits of the serverless framework in general.

**Comment by schickling** [comment]
Thanks a lot for your kind words @kopertop! Would you mind digging into this and creating a PR for it?

**Comment by kopertop** [comment]
Digging further into this, it looks like deploying just a single function using ```sls deploy function -f <funcName>``` doesn't work either.

I'm very new to Serverless Framework (I've been using Apex for the past few years), but I'll take a look. Perhaps there's a different hook this should be using.

**Comment by schickling** [comment]
Thanks a lot for your work @kopertop! Really looking forward to your contribution!

**Comment by kopertop** [comment]
I added a potential PR to make this work, although I'm not sure if I did the types right. I got it working for me but I'm not sure if it's "done right" so please take a look and let me know what i should fix.
