### ISSUE TITLE
tsconfig.json outDir is ignored?

### ISSUE THREAD

**Issue by jfgrissom** [graphcool/serverless-plugin-typescript#83]
Hi,

I noticed something that may or may not be significant.

```
#serverless.yml 

plugins:
  - serverless-plugin-typescript
```

```
#tsconfig.json
    "outDir": "SuperFlyOutDir",
```

If I run tsc
```
tsc
# Creates a directory named SuperFlyOutDir.
ls -alh
drwxr-xr-x   11 jfgrissom  staff   352B Feb  6 20:16 SuperFlyOutDir
```

If I run serverless invoke local
```
serverless invoke local -f someFunctionName
# Creates a .build directory instead of SuperFlyOutDir.
```

This seems broken? But I'm not sure if there is just something I'm missing.

### Current behavior:
Regardless of the value put in ourDir (build, deploy, SuperFly) .build is always created.

### Expected behavior:
sls invoke should build a dir named SuperFlyOutDir not .build

Is this a correct assessment or am I missing something?

**Comment by Vadorequest** [comment]
It's in the doc, outDir cannot be overridden. I guess it's on purpose to avoid side effects?

https://github.com/graphcool/serverless-plugin-typescript#tsconfigjson

**Comment by Vadorequest** [comment]
@jfgrissom

**Comment by jfgrissom** [comment]
@Vadorequest - I completely missed those notes in the docs.

Thanks for the response. It's a shame those can't be overridden.
