### ISSUE TITLE
Support extra files?

### ISSUE THREAD

**Issue by kopertop** [graphcool/serverless-plugin-typescript#9]
It looks like the code does not include any "extra" files that aren't typescript.

For example, I have a "templates" directory of handlebars templates that are not included. I see the plugin supports the "exclude" part of the package directive, but nothing for "include".

**Comment by schickling** [comment]
Agree, there's no particular reason that this shouldn't be possible. We just haven't had this requirement ourselves yet. Would you be open to create a PR for this?

**Comment by kopertop** [comment]
I'm actually working on this now, so I should have something shortly!
